server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emsAuthDB?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace

