server:
  port: 8081
  servlet:
    session:
      cookie:
        name: KSESSION
security:
  oauth2:
    client:
      client-id: web
      client-secret: web
      user-authorization-uri: http://localhost:9191/oauth/authorize
      access-token-uri: http://localhost:9191/oauth/token
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emsDataDB
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
